Add functionality of creating and updating classroom information for hardware department
TA-Software/RoundingPortal pull request #24
Opened 2022-11-09 08:19 UTC by CoreVisional

The hardware department should have the functionality of inputting classroom information while also being able to edit the information or remove a classroom.

2022-12-06 07:09 UTC, ErwinSuwito requested changes

2022-12-06 07:09 UTC, ErwinSuwito commented on RoundingPortal.Web/RoundingPortal.Web.csproj
> +	<PackageReference Include="Payroll.EntityModels" Version="1.5.0" />
Please update Payroll.EntityModels to version 1.5.1 on all projects

2022-12-06 07:12 UTC, ErwinSuwito requested changes

2022-12-07 09:35 UTC, ErwinSuwito requested changes

2022-12-07 09:35 UTC, ErwinSuwito commented on RoundingPortal.EntityModels/Models/Location.cs
> +        public string ClassroomName { get; set; }
ClassroomName could be renamed to `Name` or `RoomName`

2022-12-07 09:37 UTC, ErwinSuwito commented on RoundingPortal.Web/Controllers/LocationsController.cs
> +            vm.Locations = locationService.GetAll();
If your view only shows a list of locations, why not just use IEnumerable for your view's view model?

2022-12-08 01:56 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Controllers/HomeController.cs
> +    [Authorize(Roles = "Admin.Global")]
Added specified roles in commit "[9b02aa9]"

2022-12-08 02:42 UTC, CoreVisional commented on RoundingPortal.EntityModels/Models/Location.cs
> +        public string ClassroomName { get; set; }
Updated in commit "[5df30fe]"

2022-12-13 11:51 UTC, ErwinSuwito requested changes

2022-12-13 11:51 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Controllers/LocationsController.cs
> +                ViewBag.HtmlStr = "<h3>All Locations</h3>";
Since all of them are using h3, why not put the H3 inside the view itself and you just pass the string that's supposed to be inside. Also, you can do it in a similar way to `ViewData["Title"]`

2022-12-13 11:51 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Controllers/LocationsController.cs
> +                return NotFound();
If you're returning something like this you can remove the braces and directly write return `NotFound();` under the if statement

2022-12-13 11:51 UTC, ErwinSuwito commented on RoundingPortal.Web/Views/Shared/_LoginPartial.cshtml
> +                    var isAdmin = 0;
Why is this needed?

2022-12-13 11:51 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Views/Locations/Index.cshtml
> +            <div class="location-card__item location-card-flex">
Is it possible to base your card to be based on Bootstrap's card classes?

2022-12-13 11:51 UTC, ErwinSuwito commented on RoundingPortal.Services/LocationService.cs
> +        public IQueryable<Location> GetByCampus(string[] campus)
If its `GetByCampus` why are you accepting an array of string?

2022-12-13 12:29 UTC, CoreVisional commented on RoundingPortal.Web/Views/Shared/_LoginPartial.cshtml
> +                    var isAdmin = 0;
Updated in commit "[b87784e]" as I forgot to remove that.

2022-12-13 12:46 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Controllers/LocationsController.cs
> +                return NotFound();
Amended in commit "[f3ebc09]"

2022-12-13 13:00 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Controllers/LocationsController.cs
> +                return NotFound();
Added back the curly braces in commit "[7b4771f]"

2022-12-13 17:44 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Views/Locations/Index.cshtml
> +            <div class="location-card__item location-card-flex">
I'm sure it's possible. Initially, I wanted to use Bootstrap's card version, but I had this in mind, and I already have a working version similar to what I wanted, so I just used it instead of the Bootstrap version, though it should be possible.

2022-12-13 17:45 UTC, CoreVisional commented on RoundingPortal.Services/LocationService.cs
> +        public IQueryable<Location> GetByCampus(string[] campus)
In my controller, I have an array of string `var campuses = new[] { "APU", "APIIT" };` that is to be passed into the parameter.

2022-12-14 06:26 UTC, ErwinSuwito commented on RoundingPortal.Services/LocationService.cs
> +        public IQueryable<Location> GetByCampus(string[] campus)
If its `GetByCampus` it should be looking for one campus only.

2022-12-14 07:10 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Controllers/LocationsController.cs
> +                ViewBag.HtmlStr = "<h3>All Locations</h3>";
Updated in commit "[bd13834]"

2022-12-14 07:16 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Models/ManageLocationsIndexViewModel.cs
> +    public int APUClassrooms { get; set; }
Updated in commit "[44f484f]"

2022-12-14 07:16 UTC, ErwinSuwito requested changes

2022-12-14 07:16 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Controllers/LocationsController.cs
> +                ViewData["h3Tags"] = "All Locations";
Please rename this with a more descriptive name, for example `pageHeader`

2022-12-14 07:23 UTC, ErwinSuwito requested changes

2022-12-14 07:23 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Views/Locations/Summary.cshtml
> +                            <button type="submit" class="btn btn-danger btn-sm">
Would be better to instead of directly deleting the location when the user clicks on it, ask them for confirmation as this is a destructive action.

2022-12-14 07:23 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Controllers/LocationsController.cs
> +                    if (ModelState.IsValid)
I don't think you would need to check if ModelState is valid or not for this controller action

2022-12-14 15:13 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Controllers/LocationsController.cs
> +        public IActionResult Summary(string query)
Updated in commit "[774c2c3]"

2022-12-14 15:14 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Controllers/LocationsController.cs
> +                    if (ModelState.IsValid)
Updated in commit "[82c2130]"

2022-12-15 09:38 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Controllers/LocationsController.cs
> +                ViewData["h3Tags"] = "All Locations";
I'm assuming you mean both "Title" and "h3Tags" or is it only "Title"?

2022-12-15 09:39 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Views/Locations/Summary.cshtml
> +                            <button type="submit" class="btn btn-danger btn-sm">
Actually, I was considering this, but then it seems like even if they accidentally deleted it, it would not be troublesome to re-create it again.

2022-12-15 10:03 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Views/Locations/Summary.cshtml
> +                            <button type="submit" class="btn btn-danger btn-sm">
For now, it's not that troublesome, but what happens later when more objects are dependent on this?

2022-12-15 10:03 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Controllers/LocationsController.cs
> +                ViewData["h3Tags"] = "All Locations";
`h3Tags` only

2022-12-15 13:57 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Controllers/LocationsController.cs
> +                ViewData["h3Tags"] = "All Locations";
Updated in commit "[d06c799]"

2022-12-15 13:58 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Views/Locations/Summary.cshtml
> +                            <button type="submit" class="btn btn-danger btn-sm">
Alright, will add the confirmation prompt before deleting an item.

2022-12-16 10:29 UTC, CoreVisional commented on RoundingPortal.Services/LocationService.cs
> +        public IQueryable<Location> GetByCampus(string[] campus)
I'm assuming you mean the naming for the method here is odd? Where it should be something like `GetByCampuses`?

2022-12-16 10:39 UTC, ErwinSuwito commented on RoundingPortal.Services/LocationService.cs
> +        public IQueryable<Location> GetByCampus(string[] campus)
No the method itself. See my other comments

2022-12-16 11:07 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Controllers/LocationsController.cs
> +            var apuClassrooms = allClassrooms.Where(x => x.Campus == campuses[0]).Count();
Updated in commit "[c95e964]"

2022-12-17 07:01 UTC, CoreVisional commented on RoundingPortal.Services/LocationService.cs
> +        public IEnumerable<Location> GetByRoute(string indicator)
Updated in commit "[22acaab]"

2022-12-18 13:39 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Views/Locations/Summary.cshtml
> +                            <button type="submit" class="btn btn-danger btn-sm">
Added the confirm delete modal in commit "[1b7d29f]".

Fixed minor issue in commit "[5ee0a8e]" immediately after adding the modal as the issue was found upon testing it right after adding the modal.

2022-12-19 07:39 UTC, ErwinSuwito commented on RoundingPortal.Services/LocationService.cs
> +        public IEnumerable<Location> GetByRoute(string indicator)
Please rename `indicator` to something like `campus`

2022-12-19 07:55 UTC, CoreVisional commented on RoundingPortal.Services/LocationService.cs
> +        public IEnumerable<Location> GetByRoute(string indicator)
Updated in commit "[18d6b88]"

2022-12-19 09:45 UTC, ErwinSuwito approved these changes

2022-12-19 09:45 UTC, merged