Start screen
TA-Software/RoundingPortal pull request #35
Opened 2023-01-07 14:48 UTC by Abdos2004

Start Page for Rounding Portal

2023-01-07 14:50 UTC, ErwinSuwito requested changes

2023-01-07 14:50 UTC, ErwinSuwito commented on RoundingPortal.Functions.UserSynchronization/Startup.cs
> +    public void ConfigureServices(IServiceCollection services) => services.AddMvcCore().AddRazorPagesOptions(options =>
Why this change? It's not really part of the web app but a function that is deployed to azure separately

2023-01-07 14:50 UTC, ErwinSuwito commented on RoundingPortal.Web/Controllers/StartController.cs
> +    public class StartController : Controller
Instead of creating a new controller, you could've modified the content of `Index.cshtml` on `Views/Home/Index.cshtml`

2023-01-07 14:51 UTC, ErwinSuwito commented on RoundingPortal.Web/Models/StartModel.cs
> +    [AllowAnonymous]
You don't need the `AllowAnonymous` annotation as it is a model

2023-01-07 19:39 UTC, Abdos2004 commented on RoundingPortal.Web/Models/StartModel.cs
> +    [AllowAnonymous]
Removed [AllowAnonymous] as it is unneeded

2023-01-07 19:40 UTC, Abdos2004 commented on RoundingPortal.Web/Controllers/StartController.cs
> +    public class StartController : Controller
Edited the the Views/Home/Index.cshtml and removed the start/index.cshtml

2023-01-07 19:40 UTC, Abdos2004 commented on RoundingPortal.Functions.UserSynchronization/Startup.cs
> +    public void ConfigureServices(IServiceCollection services) => services.AddMvcCore().AddRazorPagesOptions(options =>
Noted and removed

2023-01-07 23:38 UTC, ErwinSuwito requested changes

2023-01-07 23:38 UTC, ErwinSuwito commented on RoundingPortal.Functions.UserSynchronization/Startup.cs
> +    //public void ConfigureServices(IServiceCollection services) => services.AddMvcCore().AddRazorPagesOptions(options =>
You can just remove this, it's not supposed to be there

2023-01-07 23:38 UTC, ErwinSuwito commented on RoundingPortal.Web/Controllers/HomeController.cs
> +    public class StartController : Controller
This is not needed as you moved the content to the correct view already.

2023-01-07 23:38 UTC, ErwinSuwito commented on RoundingPortal.Web/Controllers/HomeController.cs
> +
Please remove the empty lines

2023-01-07 23:38 UTC, ErwinSuwito commented on RoundingPortal.Web/Models/StartModel.cs
> +    public class StartModel
You don't need this either.

2023-01-08 11:00 UTC, Abdos2004 commented on RoundingPortal.Web/Models/StartModel.cs
> +    public class StartModel
Deleted the unneeded model

2023-01-08 11:00 UTC, Abdos2004 commented on RoundingPortal.Web/Controllers/HomeController.cs
> +
Done

2023-01-08 11:00 UTC, Abdos2004 commented on RoundingPortal.Web/Controllers/HomeController.cs
> +    public class StartController : Controller
Removed

2023-01-08 11:00 UTC, Abdos2004 commented on RoundingPortal.Functions.UserSynchronization/Startup.cs
> +    //public void ConfigureServices(IServiceCollection services) => services.AddMvcCore().AddRazorPagesOptions(options =>
Removed

2023-01-08 14:48 UTC, ErwinSuwito approved these changes

2023-01-08 14:49 UTC, merged