Edited "Add Location" dropdown button
TA-Software/RoundingPortal pull request #36
Opened 2023-01-07 19:43 UTC by Abdos2004

Edited the Add Location button in the admin side

2023-01-07 23:49 UTC, ErwinSuwito requested changes

2023-01-07 23:49 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Views/Locations/Index.cshtml
> +            <!--<a class="dropdown-item" href="@Url.Action("Create", "Locations")">Add Single Location</a>-->
You can just remove this line as its not needed anymore

2023-01-08 10:37 UTC, Abdos2004 commented on RoundingPortal.Web/Areas/Admin/Views/Locations/Index.cshtml
> +            <!--<a class="dropdown-item" href="@Url.Action("Create", "Locations")">Add Single Location</a>-->
Line removed

2023-01-08 14:50 UTC, ErwinSuwito approved these changes

2023-01-08 14:50 UTC, merged