Add and modify device specifications for each device model
TA-Software/RoundingPortal pull request #39
Opened 2023-03-27 15:20 UTC by CoreVisional

Hardware Department can view, add, edit, or remove single or multiple device specifications from a device model as well as regular user should be able to view them as well.

2023-04-01 23:51 UTC, ErwinSuwito commented on RoundingPortal.EntityModels/ViewModels/DeviceSpecificationViewModel.cs
What is this class used for?

2023-04-01 23:51 UTC, ErwinSuwito commented on RoundingPortal.Web/Views/DeviceModels/Details.cshtml
>  <div>
You can move this into a partial view and pass the model into it, then use it in both the main site and Admin area

2023-04-02 05:05 UTC, CoreVisional commented on RoundingPortal.EntityModels/ViewModels/DeviceSpecificationViewModel.cs
Removed in commit "[a2ad737]". It was added initially before the use of an API controller to help display data. But it wasn't needed anymore since a DeviceModelDetailsViewModel was created to display the data.

2023-04-02 06:20 UTC, CoreVisional commented on RoundingPortal.Web/Views/DeviceModels/Details.cshtml
>  <div>
Updated in commits "[19ea229] (Adding the partial view)" and "[3c4b8b5](Call the partial view asynchronously)"

2023-04-02 08:31 UTC, ErwinSuwito requested changes

2023-04-02 08:31 UTC, ErwinSuwito commented on RoundingPortal.Web/Views/Shared/_DeviceModelDetailsPartial.cshtml
> +    bool isAdmin = ViewData["IsAdmin"] as bool? ?? false;
I understand what you're trying to do here. But you can either use `User.IsInRole` or use ViewContext to get Area value (see https://github.com/TA-Software/Payroll/blob/129aed30a00e1e9639eb1fea23e2ab45dda3176e/Payroll.Web/Views/Shared/_LoginPartial.cshtml#L25)

2023-04-02 09:45 UTC, ErwinSuwito approved these changes

2023-04-02 09:46 UTC, merged