Adding devices to each room location
TA-Software/RoundingPortal pull request #40
Opened 2023-04-12 04:23 UTC by CoreVisional

Hardware department should be able to add, edit (including reassignment of devices to another location), remove, and bulk upload devices to a location based on the device model and room location that are already added to the system

2023-04-12 06:53 UTC, ErwinSuwito requested changes

2023-04-12 06:53 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Controllers/RoomDevicesController.cs
> +            return View(device);
If this fails in any way, the selection for `ModelName` and `RoomName` will be empty

2023-04-12 06:53 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Controllers/RoomDevicesController.cs
> +            return RedirectToAction("Index");
Same with the above

2023-04-12 06:53 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Views/Devices/Index.cshtml
> +                <a class="dropdown-item" href="#">Device</a>
It's probably better to make this link also work

2023-04-12 06:53 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Views/Locations/Details.cshtml
> +            <button type="button" class="btn btn-primary btn-sm shadow-sm">Add New Location</button>
This link too

2023-04-12 06:53 UTC, ErwinSuwito commented on RoundingPortal.Web/Areas/Admin/Views/RoomDevices/Index.cshtml
> +        <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown">
This too

2023-04-12 06:53 UTC, ErwinSuwito commented on RoundingPortal.Web/Models/DeviceDetailsViewModel.cs
> +public class DeviceDetailsViewModel
If this class only contains `Device`, why not directly use the model itself?

2023-04-12 06:53 UTC, ErwinSuwito commented on RoundingPortal.Web/Views/Shared/_DevicesDetailsPartial.cshtml
> +                <button type="button" class="btn btn-primary">Add Device</button>
This link too

2023-04-13 08:04 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Controllers/RoomDevicesController.cs
> +            return View(device);
May I know if it is the `Create` method? If so, a default value can be given from the view instead.

2023-04-13 10:12 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Views/Locations/Details.cshtml
> +            <button type="button" class="btn btn-primary btn-sm shadow-sm">Add New Location</button>
Updated in commit "[c063629]"

2023-04-13 10:14 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Views/Devices/Index.cshtml
> +                <a class="dropdown-item" href="#">Device</a>
Updated in commit "[3ee3ba7]"

2023-04-13 10:18 UTC, CoreVisional commented on RoundingPortal.Web/Views/Shared/_DevicesDetailsPartial.cshtml
> +                <button type="button" class="btn btn-primary">Add Device</button>
Updated in commit "[587989b]"

2023-04-13 10:55 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Controllers/RoomDevicesController.cs
> +            return RedirectToAction("Index");
Updated in commit "[16f8eb5]"

2023-04-13 12:47 UTC, CoreVisional commented on RoundingPortal.Web/Models/DeviceDetailsViewModel.cs
> +public class DeviceDetailsViewModel
Updated in the following commits:

- Commit [08aa761] - Removed DeviceDetailsViewModel

- Commit [39748ee] - Add a method in DeviceService to get the related entities

- Commit [d24eee9] - Update the necessary lines in RoomDevicesController for both admin and non-admin area

- Commit [01f4ec1] - Update _DeviceDetailsPartial and both Details.cshtml in admin and non-admin area to use directly use the model itself

2023-04-13 17:58 UTC, CoreVisional commented on RoundingPortal.Web/Areas/Admin/Controllers/RoomDevicesController.cs
> +            return View(device);
Updated in the following commits for Create and Edit POST endpoints:

- Commit [5fddc2d] - Add a ManageDeviceFormViewModel to use view model instead of ViewBag
- Commit [38d2e6c] - Update Edit.cshtml to use the view model
- Commit [7ba479a] - Update Create.cshtml to use the view model
- Commit [584d419] - Update Edit POST endpoint in RoomDevicesController to use ManageDeviceFormViewModel
- Commit [68012e1] - Update Create POST endpoint in RoomDevicesController to pass in the view if ModelState is invalid

2023-04-14 11:52 UTC, ErwinSuwito approved these changes

2023-04-14 11:52 UTC, merged